CREATE TABLE languages 
(
    language_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(32) NOT NULL,
    code VARCHAR(5) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_languages PRIMARY KEY (language_id),
    CONSTRAINT uq_languages_code UNIQUE (code)
);