CREATE TABLE users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_group_id INTEGER NOT NULL,
    username VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    active_directory_guid UUID,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    origin VARCHAR(5) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_users PRIMARY KEY(user_id),
    CONSTRAINT fk_users_user_group FOREIGN KEY(user_group_id) REFERENCES user_groups(user_group_id)
);