CREATE TABLE form_status
(
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_form_status PRIMARY KEY(status_id)
);