CREATE TABLE forms
(
    form_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    logo BYTEA,
    image BYTEA,
    login_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    default_status_id INTEGER NOT NULL,
    language_id INTEGER NOT NULL,
    default_name VARCHAR(50) NOT NULL DEFAULT '',
    CONSTRAINT pk_forms PRIMARY KEY (form_id),
    CONSTRAINT fk_status FOREIGN KEY (default_status_id) REFERENCES form_status(status_id),
    CONSTRAINT fk_language FOREIGN KEY (language_id) REFERENCES languages(language_id) ON DELETE CASCADE ON UPDATE CASCADE
);
