//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorForms.Web.Languages.Components.Pages.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorForms.Web.Languages.Components.Pages.Admin.FormStatus", typeof(FormStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form statuses.
        /// </summary>
        public static string BREADCRUMB_LIST {
            get {
                return ResourceManager.GetString("BREADCRUMB_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete status.
        /// </summary>
        public static string BUTTON_DELETE_STATUS {
            get {
                return ResourceManager.GetString("BUTTON_DELETE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New form status.
        /// </summary>
        public static string CREATE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("CREATE_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is completed.
        /// </summary>
        public static string LABEL_IS_COMPLETE {
            get {
                return ResourceManager.GetString("LABEL_IS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires approval.
        /// </summary>
        public static string LABEL_REQUIRES_APPROVAL {
            get {
                return ResourceManager.GetString("LABEL_REQUIRES_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string LABEL_SORT_ORDER {
            get {
                return ResourceManager.GetString("LABEL_SORT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form statuses.
        /// </summary>
        public static string LIST_PAGE_TITLE {
            get {
                return ResourceManager.GetString("LIST_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New form status.
        /// </summary>
        public static string NEW_STATUS {
            get {
                return ResourceManager.GetString("NEW_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name.
        /// </summary>
        public static string SEARCH_PHRASE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("SEARCH_PHRASE_PLACEHOLDER", resourceCulture);
            }
        }
    }
}
