CREATE TABLE roles
(
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    active_directory_group_cn VARCHAR(255) NOT NULL DEFAULT '',
    can_be_deleted BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_user_groups PRIMARY KEY (role_id)
);